### ISSUE TITLE
리트코드 클래스로 구현되있는걸 에디터에 코드 구현하는 법 질문

### ISSUE THREAD

**Issue by nickhealthy** [onlybooks/algorithm-interview#110]
안녕하세요 알고리즘 책 아주 유익하게 잘 읽고 있습니다.
다름이 아니라 리트코드 내에서 바로 웹 에디션을 쓰는게 아니라
로컬 에디터를 이용해(vscode) 코딩을 하고 있습니다.
```
# Definition for singly-linked list.
class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

class Solution:
    def reverseList(self, head):
        def reverse(node, prev):
            if not node:
                return prev
            next, node.next = node.next, prev
            return reverse(next, node)

        return reverse(head, ListNode = None)

head = ListNode([1,2,3,4,5])
test = Solution()
print(test.reverseList(head))
```
연결 리스트 15번 문제 같은 경우에는 어떤 식으로 코드를 해야 제 에디터에서 직접 돌려볼 수 있나요 ??
에디터 사용은 디버깅 목적으로 사용하려고 개인 에디터에서 작성중입니다.
(제가 위와 같이 에디터에 작성하고 돌려봤는데 안되더라구요.. 클래스를 잘 모르는 영향도 있긴합니다.)

추가로 14번 문제도 로컬 에디터에서 어떻게 구현하면 되는지 알려주시면 감사하겠습니다 !

**Comment by DoTheBestMayB** [comment]
1. 입력값이 잘못되었습니다. ListNode([1,2,3,4,5]) 는 잘못된 코드입니다. ListNode 클래스의 init 매개변수를 보시면 입력받는 값이 val 과 next 인 것을 알 수 있습니다. 기본 default 값이 있어서 전달해주지 않아도 되긴합니다.
저는 에디터에서 테스트 해보기 위해 리스트 값([1,2,3,4,5])을 ListNode로 변경해주는 makeNode 함수를 만들어서 사용했습니다.

2. 출력하는 방법이 잘못되었습니다. reverseList 의 결과물은 ListNode 한 변수 입니다.
그냥 print 하면 변수가 가리키는 주소값이 나옵니다.
질문자님이 의도한 대로 출력해보기 위해서는, 연결리스트를 출력하는 방법을 사용해야 합니다.

```
# Definition for singly-linked list.
class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

class Solution:
    def reverseList(self, head):
        def reverse(node, prev):
            if not node:
                return prev
            next, node.next = node.next, prev
            return reverse(next, node)

        return reverse(head, None)


def makeNode(lst):
    res = ptr = ListNode()
    for item in lst:
        ptr.next = ListNode(item)
        ptr = ptr.next

    return res.next


head = makeNode([1,2,3,4,5])
ans = Solution().reverseList(head)

while ans:
    print(ans.val, end=' ')
    ans = ans.next
```

**Comment by likejazz** [comment]
@DoTheBestMayB 답변주셔서 감사합니다. @nickhealthy 저런 식으로 ListNode를 구현하는 코드를 직접 만들어서 입력값으로 제공하시면 됩니다.
