### ISSUE TITLE
과반수 엘리먼트 p615 질문입니다.

### ISSUE THREAD

**Issue by AsterGoldman** [onlybooks/algorithm-interview#117]
파이써닉 방식으로
`return sorted(nums)[len(nums)//2]`

한 줄 코드를 제시했는데 반례로
[1,2,3,4,5,5,6]이 제시되는 경우 최빈값인 5가 아닌 4가 나오게 됩니다

**Comment by likejazz** [comment]
@AsterGoldman 안녕하세요. 문제가 최빈값을 추출하는 게 아닌 과반수를 초과하는 수를 찾는 문제 입니다. 따라서 중앙값을 추출하면 항상 정답이 나오게 됩니다.
