### ISSUE TITLE
typo report (p.282 && p.331)

### ISSUE THREAD

**Issue by miknai** [onlybooks/algorithm-interview#12]
// p.282
아래서 3 번째줄, "10개의 공간중" -> "9개의 공간중" 으로 바뀌어야 될거같습니다. 

// p.331
두번째 예제 출력, "1" -> "3"

**Comment by likejazz** [comment]
감사합니다.
정오표에 반영하였습니다. https://www.onlybook.co.kr/entry/algorithm-interview-errata
