### ISSUE TITLE
가장 긴 팰린드롬 문제 관련해서 질문드립니다

### ISSUE THREAD

**Issue by ibot615** [onlybooks/algorithm-interview#122]
제가 프로그래밍에 아직 익숙치 않아서 질문드립니다.
책에 수록된 코드를 보면 
result = ''
for i in range(0, len(s)-1):
    result = max(result, expand(i,i+1),expand(i,i+2),key=len)
부분이 있는데 위 코드에서 expand(i,i+2)가 i 값이 len(s)-1일 때 어떻게 인덱스 초과 관련하여 오류가 생기지 않고 
정상적으로 동작하게 되는지 궁금합니다.

**Comment by PARKINHYO** [comment]
for문의 범위 `range()`에서 안의 범위 끝을 `len(s)-1`로 줬을 때 실제로 i는 len(s)-2까지만 진행하게 됩니당
만약 `for i in range(0, 5)`라면 i는 0, 1, 2, 3, 4까지만 돌게 되는거죵
