### ISSUE TITLE
p.g 194 11번 문제 질문 있습니다

### ISSUE THREAD

**Issue by chanwon2** [onlybooks/algorithm-interview#130]
코드를 보면 마지막에
for i in range(len(nums) -1, 0 - 1, -1):로 역순으로 반복문을 실행하는데
2번째 파라미터 부분을 0-1로 쓴 이유가 궁금합니다. 
-1로 작성시 정상적으로 출력이 되서 0-1로 작성해야 되는 이유가 따로 있는 건가요?

**Comment by likejazz** [comment]
가독성을 높이기 위해 그렇게 작성하였습니다. `0 - 1`은 0까지 반복되기 때문에 그냥 `-1`로 두는 것에 비해 훨씬 더 직관적입니다.
