### ISSUE TITLE
p.613 비둘기집 원리 페이지 번호 오타

### ISSUE THREAD

**Issue by DoTheBestMayB** [onlybooks/algorithm-interview#132]
28페이지 참고가 아니라 282페이지 참고 같아요

**Comment by onlybooks** [comment]
안녕하세요. 독자님. 말씀하신 사항은 282페이지가 맞습니다. 해당 사항은 정오표에 등록하고 증쇄시에 반영해두겠습니다. 알려주셔서 감사합니다.
