### ISSUE TITLE
디렉터리명, 파일명 변경 제안드립니다.

### ISSUE THREAD

**Issue by ichdich** [onlybooks/algorithm-interview#133]
좋은 책 감사드립니다.
다름이 아니라 파이썬 쉘에서 import 해서 사용하기 쉽게 아래와 같은 형태로 디렉터리명, 파일명 변경을 제안드립니다.
(변경 전) 2-python/ch06/1-1.py
(변경 후) ch02_python/ch06/ex1_1.py

이렇게 변경하면 파이썬 쉘에서 아래처럼 코드를 돌려볼 수 있을 것 같습니다.
>>> from ch02_python.ch06.ex1_1 import Solution
>>> s=Solution()
>>> s.isPalindrome("blah blah blah")

변경하지 않으면 import 할 때 에러가 발생합니다.
검토 부탁드립니다.

**Comment by likejazz** [comment]
좋은 제안 감사드립니다. 원래 이 책의 코드는 로컬에서 돌리는 용도가 아니라 리트코드 제출 용도로 구성하다 보니 그런 부분은 미처 고려하지 못했습니다. 추후에 개정판을 내게 된다면 적극 검토하도록 하겠습니다.
