### ISSUE TITLE
p298 29번 문제 질문입니다

### ISSUE THREAD

**Issue by heesungkim010** [onlybooks/algorithm-interview#139]
풀이 4에서 리스트 컴프리헨션 부분에서 질문입니다.
두 문자열의 길이를 각각 m, n이라고 가정했습니다.

1. 리스트 컴프리헨션으로 풀이하면 빅오가 O( m * n ) 로 될거 같은데 맞나요?

2. 그리고 풀이 1,2,3 은 빅오가 O( m +n ) 으로 나올거같은데요. 그래서 풀이 1,2,3이 풀이 4보다 더 빠를거라고 생각했는데 실행 시간은 왜 비슷한건가요??

**Comment by likejazz** [comment]
말씀하신대로 시간 복잡도를 고려하면 풀이 1,2,3이 더 효율적인 방식이고 좋은 풀이라고 할 수 있습니다. 4가 더 느려야 하지만 여기서는 테스트케이스가 시간 복잡도에 영향을 받을만큼 충분히 크지 않거나 또는 리스트 컴프리헨션이 워낙 빠르기 때문으로 추정할 수 있습니다. 파이썬에서 for 문을 직접 반복하는 것보다는 내부적으로 C 모듈로 동작하는 리스트 컴프리헨션이 일반적으로 더 빨리 수행됩니다.
