### ISSUE TITLE
p.455 이진 힙 추출 시간 복잡도 관련 질문

### ISSUE THREAD

**Issue by hy-yoo** [onlybooks/algorithm-interview#148]
안녕하세요~ 좋은 책 내주셔서 감사합니다. 🙇‍♀️ 

p.455의 참고 섹션에서 이진 힙과 BST를 비교하고 있는데요.
> ... 반면 가장 큰 값을 추출하거나 가장 작은 값을 추출하려면 이진 힙을 사용해야 한다. 이진 힙은 이 작업이 O(1)에 가능하다.

이런 내용이 있습니다.

저는 이진 힙은 추출 후에도 힙의 특성을 유지하기 위한 작업이 필요하기 때문에, 추출 작업에는 O(logN)이 소요된다고 이해했습니다. 제가 이해한 바가 맞다면, 참고 섹션에서 말하는 이진 힙의 추출 작업 소요시간이 O(logN)이 되거나 아니면 조회가 O(1)이어야 할 것 같은데요..!

혹시 제가 잘못 이해한 부분이 있는 걸까요?

**Comment by likejazz** [comment]
네 맞습니다. 말씀하신대로 전체 과정은 O(logn)이 맞습니다. 책에서는 find min/max의 경우를 얘기한 것이고 여기에 heapify 과정 등의 언급은 생략하다 보니 충분한 설명이 부족했던거 같습니다. 정오표에는 '추출' 대신에 '조회'라는 표현으로 수정하도록 하겠습니다. 알려주셔서 감사합니다.

**Comment by onlybooks** [comment]
해당 내용은 이 책의 공식 정오표 페이지에 올려뒀습니다. 오류 사항 알려주셔서 고맙습니다. 추후 증쇄시에도 반영하겠습니다.
<파이썬 알고리즘 인터뷰> 정오표 : https://www.onlybook.co.kr/entry/algorithm-interview-errata
