### ISSUE TITLE
typo report(p.350)

### ISSUE THREAD

**Issue by KoEonYack** [onlybooks/algorithm-interview#15]
위에서 6번째 줄

__[책 내용]__ 이 경우 앞서 순열의 결과인 60에서 6을 나눈 `6/60 = 10`이 된다.

__[수정]__ 이 경우 앞서 순열의 결과인 60에서 6을 나눈 `60/6 = 10`이 된다.

분모와 분자를 바꾸어야 합니다.

>

설명도 쉽게 되어있고 다양한 각도에서  접근한 코드를 보며 책 재미있게 보고 있습니다. 감사합니다!

AI 분야 책을 쓰실 예정은 없으신가요?? 기대됩니다!

**Comment by likejazz** [comment]
감사합니다.
정오표에 반영하겠습니다.

저희 책 재미있게 봐주셔서 감사합니다. AI 분야도 당연히 써보고 싶은 마음은 있는데 책 한 권 쓰는 일이 몇 년씩 걸리는 쉽지 않은 일이고, 이미 AI/ML 분야에는 너무 많은 책들이 출간된 상태라 선뜻 나서기가 쉽지 않습니다.

책 많이 홍보해주시고 리뷰도 부탁드립니다 ^^
감사합니다.
