### ISSUE TITLE
13번 팰린드롬 연결리스트 문제 runtime

### ISSUE THREAD

**Issue by cozytk** [onlybooks/algorithm-interview#155]
13-4.py파일에 해당하는 13번 팰린드롬 연결리스트 문제 테스트 케이스 추가로 runtime이 전체적으로 증가한건가요?
<img width="712" alt="스크린샷 2022-03-24 오후 5 44 27" src="https://user-images.githubusercontent.com/59143479/159877161-a89e71d2-f528-4a68-be20-6030cb73880c.png">
13-4.py 문제와 동일하게 제출했는데 600ms 이상 나왔습니다! 본문에는 64ms로 나와있어요!!

**Comment by likejazz** [comment]
안녕하세요. 리트코드의 테스트케이스는 지속적으로 수정되고 있습니다. 어떤 문제는 테스트케이스를 대폭 줄이기도 하고, 어떤 문제는 늘리기도 합니다. 책이 출간된지도 어느덧 2년이 다 되어 가기 때문에 그때에 비해 테스트케이스가 많이 수정되었고, 한 번 출간되면 수정이 불가능한 책의 특성상 지속적인 업데이트는 어려움을 양해 부탁드립니다. 물론 테스트케이스가 변경되어도 각 풀이별 실행 속도의 차이는 비슷할 것이기 때문에 참고하시면 될거 같습니다.
