### ISSUE TITLE
p. 578 문법 질문 드립니다

### ISSUE THREAD

**Issue by lgkrwnsdll** [onlybooks/algorithm-interview#157]
`missing -= need[char] > 0`

정답 코드 중 missing 변수가 1씩 줄어드는 구현을 이렇게 표현하신 것 같은데,
a -= b > 0 꼴에서 복합 대입 연산 이후에 부등호가 어떤 의미를 가져서 이 코드가 1씩 빼는 수행을 하는지 궁금합니다.
need[char] 값이 1이 아니어도 1씩 줄어드는데, 잘 이해가 가지 않아 질문드립니다.
감사합니다!

**Comment by likejazz** [comment]
@lgkrwnsdll 안녕하세요. 이슈가 closed되어 있어서 답변 드리지 못하고 놓쳤네요. 저 부분은 `need[char] > 0`가 `True`이면 `1`, `False`이면 `0`이 됩니다. 즉 `need[char]`가 0보다 크면 `missing` 변수가 1씩 줄어들게 됩니다.
