### ISSUE TITLE
P640 오타

### ISSUE THREAD

**Issue by ruseel** [onlybooks/algorithm-interview#165]
그림 23-9 에

정상 n계단 
n-1 계단 
n-1 계단 
…

으로 인쇄되었습니다. 

정상 n계단 
n-1 계단 
n-2 계단
…

이 옳을 듯 싶습니다.

**Comment by onlybooks** [comment]
안녕하세요. 책만 출판사 편집팀입니다. 우선, 도서 읽으시는 데 불편함을 드려 죄송한 마음입니다. 
말씀하신 내용은 오류가 맞습니다. 해당 내용에 대해서는 저희 정오표에 모두 올려뒀습니다. 
https://www.onlybook.co.kr/entry/algorithm-interview-errata 

이후 증쇄된 도서에서는 다른 오류 사항도 모두 수정 발행해놓은 상태라 만약 최근에 발행된 도서를 구입하셨다면 오류가 없을 것 같습니다만, 가지고 계신 도서는 아마도 2020년 8월 즈음에 발행된 2쇄거나 초판본 1쇄일 듯합니다. 조금 번거로우시더라도 저희 사이트의 정오표 내용을 확인, 수정해 읽어주시면 감사하겠습니다.
