### ISSUE TITLE
오타 확인 부탁드립니다.

### ISSUE THREAD

**Issue by jjya1b2c3vu** [onlybooks/algorithm-interview#17]
p152

line 7
return max(counts , key=count.get)

->
return max(counts, key=counts.get)

딕셔너리 객체의 변수명이 오타난것 같습니다.

**Comment by likejazz** [comment]
오타가 맞습니다.
정오표에 반영하겠습니다. 
https://www.onlybook.co.kr/entry/algorithm-interview-errata

감사합니다!
