### ISSUE TITLE
28번문제. 해시맵 디자인

### ISSUE THREAD

**Issue by bjy3392** [onlybooks/algorithm-interview#18]
깃허브에 올라와 있는 28번 해시맵 디자인의 풀이코드에 ListNode정의하는 부분이 잘못 올라 온 것같습니다.
class ListNode:
    def __init__(self, x):
        self.val = x
        self.next = None

책내용>>
class ListNode:
    def __init__(self, key=None, value=None):
        self.key = key
        self.value = value
        self.next = None

**Comment by likejazz** [comment]
안녕하세요.
알려주셔서 감사합니다. 말씀하신대로 깃헙에서 `ListNode`는 알려주신 내용이 맞습니다.
해당 코드 반영하겠습니다.
