### ISSUE TITLE
알고리즘 공부 방법에 대한 문의

### ISSUE THREAD

**Issue by sungmin7465** [onlybooks/algorithm-interview#19]
안녕하세요. 
책에 설명된 알고리즘 문제들을 차근차근 이해하려고 노력하며 공부하고 있습니다. 
책에 소개된 문제의 코드를 직접 실행해보고 디버깅해가며 공부하고 있는데, 바보 같은 질문일 수도 있지만, 문득 드는 생각이.. 이렇게 다른 사람이 고안해낸 풀이법을 이해하며 습득하면 저도 그분들 처럼 알고리즘에 대한 풀이법을 생각해낼 수 있는 문제해결능력이 향상될 수 있는지 궁금해서 이렇게 질문드립니다. (단순히 풀이법을 따라하게 되는 것이 아닌) 알고리즘 쪽은 어떤식으로 공부해나아가야 좋을지 잘 모르겠네요..  그냥 이렇게 책의 설명과 코드를 이해하면서 공부하는게 잘하고 있는 것일까요?

감사합니다.

**Comment by likejazz** [comment]
안녕하세요.

알고리즘 공부는 수학을 공부하는 것과 크게 다르지 않습니다. 스스로 여러가지 풀이 방법을 고민하면서 문제를 풀수도 있겠지만, 아무리 해도 풀리지 않는다면 다른 사람의 풀이를 보면서 학습하는 형태로도 공부를 해야겠죠. 우리가 수학 문제를 풀다가 막히면 답안지를 보면서 풀이법을 익히는 것과 유사합니다. 물론, 단순히 풀이법을 외워서는 안되겠죠. 왜 그렇게 풀어야 하는지 이해하면서 학습하는게 가장 중요합니다.

공부에 왕도는 없습니다. 무엇보다 많이 풀어보는게 가장 중요합니다. 주변에 똑똑한 사람들이 많이 있지만 천재라서 공부하지 않고 그냥 쉽게 푸는 사람은 단 한 명도 없습니다. 잘 푸는 사람들은 다들 그만큼 많이 풀어본 사람들입니다. 리트코드 에는 1500개가 넘는 문제가 있습니다. 하루에 한 문제씩만 푼다고 해도 5년 동안 꼬박 풀어야 하는 분량이고, 연습 문제로는 충분하다고 생각되요. 많이 풀어보면서, 막히면 다른 사람의 풀이도 살펴보면서 이해하려고 꾸준히 노력해보세요.

무엇보다 지혜는 지식의 발현이라고 믿습니다. 지식을 많이 습득할수록 지혜를 발휘할 수 있다는 점 명심하시기 바랍니다.

**Comment by sungmin7465** [comment]
네,  좋은답변감사하겠습니다^^
