### ISSUE TITLE
코딩 테스트에 대한 문의

### ISSUE THREAD

**Issue by algo-risk** [onlybooks/algorithm-interview#20]
안녕하세요, 

유익하고 알찬 책을 이렇게 접할 수 있게 애써 주셔서 감사드립니다. <파이썬 알고리즘 인터뷰>를 열심히 

소화 중입니다. 책에 나오는 주 대상 언어는 아니어도 코딩 테스트 관련 대비 내용이 있으므로 SQL 코딩 테스트에 

대해서도 질문 드려도 될까요? 실시하는 회사마다 난이도가 천차만별일 수 있지만, 그래도 어느 정도 보편적인 범위의 

난이도라는 건 존재한다고 생각합니다. 어떤 테이블이 주어졌을 때 

1시간 안에 5~6개 문제 정도의 쿼리를 제출해야 하는 SQL 테스트 진행 방식이라면, 

난이도를 어느 정도로 생각하고 준비하면 통과 확률을 최대한 높일 수 있을까요? (제출 후 제출 코드에 대한 리뷰 인터뷰도 진행)

SQL 전문 개발자 포지션은 아니고 데이터 사이언스나 데이터 분석 포지션인 경우입니다. 

좀 고리타분한 시각인지 몰라도 사실 "SQL이 코딩 테스트를 할 만한 언어인가?"라는 

(더 근본적으로는 SQL도 'L'이 있다고 해도 (프로그래밍) 언어는 언어이긴 한가 하는) 느낌도 있습니다만 요즘 

SQL만으로 코딩 테스트를 진행하는 비중도 꽤 늘어나고 있는 추세 같습니다. 떠올려 보실 수 있는 팁 다양하게 

공유될 수 있으면 정말 도움이 되고 감사하겠습니다. 실무에서 꽤 써 본 경험은 있지만(개발자나 관리자는 아니라 DML 위주로) 

막상 테스팅 환경을 접해야 한다고 하니 상당히 부담이 가중됩니다. 

다소 막연한 질문 같기도 한데, 그래도 압박감이 커지고 답답해서 올리니 도움 말씀 미리 진심으로 감사드립니다.

**Comment by likejazz** [comment]
#21 Duplicated.
