### ISSUE TITLE
코딩 테스트에 대한 질문

### ISSUE THREAD

**Issue by algo-risk** [onlybooks/algorithm-interview#21]
안녕하세요,

유익하고 알찬 책을 이렇게 접할 수 있게 애써 주셔서 감사드립니다. <파이썬 알고리즘 인터뷰>를 열심히

소화 중입니다. 책에 나오는 주 대상 언어는 아니어도 코딩 테스트 관련 대비 내용이 있으므로 SQL 코딩 테스트에

대해서도 질문 드려도 될까요? 실시하는 회사마다 난이도가 천차만별일 수 있지만, 그래도 어느 정도 보편적인 범위의

난이도라는 건 존재한다고 생각합니다. 어떤 테이블이 주어졌을 때

1시간 안에 5~6개 문제 정도의 쿼리를 제출해야 하는 SQL 테스트 진행 방식이라면,

난이도를 어느 정도로 생각하고 준비하면 통과 확률을 최대한 높일 수 있을까요? (제출 후 제출 코드에 대한 리뷰 인터뷰도 진행)

SQL 전문 개발자 포지션은 아니고 데이터 사이언스나 데이터 분석 포지션인 경우입니다.

좀 고리타분한 시각인지 몰라도 사실 "SQL이 코딩 테스트를 할 만한 언어인가?"라는

(더 근본적으로는 SQL도 'L'이 있다고 해도 (프로그래밍) 언어는 언어이긴 한가 하는) 느낌도 있습니다만 요즘

SQL만으로 코딩 테스트를 진행하는 비중도 꽤 늘어나고 있는 추세 같습니다. 떠올려 보실 수 있는 팁 다양하게

공유될 수 있으면 정말 도움이 되고 감사하겠습니다. 실무에서 꽤 써 본 경험은 있지만(개발자나 관리자는 아니라 DML 위주로)

막상 테스팅 환경을 접해야 한다고 하니 상당히 부담이 가중됩니다.

다소 막연한 질문 같기도 한데, 그래도 압박감이 커지고 답답해서 올리니 도움 말씀 미리 진심으로 감사드립니다.

**Comment by likejazz** [comment]
안녕하세요?
SQL 질문이라니, 코딩 테스트와는 조금 다른 주제이긴 하지만 ^^; 일단 제가 아는 한 답변 드려보겠습니다.

SQL은 사실 언어라고 보기에는 매우 단순한 명령셋의 모음일 뿐이고, 쉽게 말해 집합과 비슷하다고 보면 될거 같습니다. 원하는 데이터를 추출하기 위해 교집합, 합집합 등을 활용해 후보군을 점점 줄여 나가는데 목적이 있는, 일종의 기능 모음이죠.

아마 시험이라면 대부분이 조금 복잡하게 그룹화 하는 문법들, `GROUP BY`, `HAVING` 등을 벗어나지 않을 것 같습니다. 또는 1:1, 1:n 관계를 이해하고 있는지 보기 위해 `INNER JOIN`, `LEFT OUTER JOIN`, `RIGHT OUTER JOIN`등을 잘 활용하는지를 묻겠죠. 크게 이 범주를 넘어서지 않을 것 같고, 특성상 코딩 테스트 처럼 테스트 환경을 제공하기는 어려워 보입니다만, 당장 실습 환경 등이 필요하다면 BigQuery에서 연습하는게 가장 편할 것 같습니다. SQL 문법도 잘 정리되어 있기 때문에 문서를 한 번 읽어보는 것만 해도 많은 도움이 될 것 같구요. https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax GCP 처음 가입하면 주는 무료 코인으로 BigQuery 연습해 볼 정도는 충분할거 같네요.

개인적으로 하나의 SQL 구문으로 모든 작업을 한 번에 처리하는 방식을 선호하지는 않습니다. 마치 파이썬 한 줄로 비지니스 로직을 한 번에 다 처리 하라는 느낌이거든요. 2-3줄로 처리해도 아무 문제가 없죠. 오히려 가독성은 훨씬 더 좋을 수 있구요. 마찬가지로 SQL도 임시 테이블을 활용해 여러번에 걸쳐 쿼리를 나눠서 처리할 수 있습니다. 어차피 데이터 분석에 사용할 SQL이니 성능 문제 때문에 못한다고 얘기하기도 어렵고요. 마찬가지로 여러번에 걸쳐 쿼리하는게 가독성은 훨씬 더 좋을 수 있죠. 면접관에게도 단일 SQL로 처리하지 않고 임시 테이블을 이용해 SQL을 여러번 활용하겠다고 충분히 어필해볼 수 있는 문제라고 생각합니다. 과거에는 뷰도 많이 활용했으나 요즘은 뷰는 잘 쓰지 않는것 같구요. 무엇보다 SQL은 그리 어려운 문법이 아니니 집합을 효율적으로 처리한다고 항상 생각하면서 다양하게 조합해보면 어렵지 않게 원하는 구문을 만들어낼 수 있을거라 생각합니다.

**Comment by algo-risk** [comment]
감사합니다!! 제가 "(더 근본적으로는 SQL도 'L'이 있다고 해도 (프로그래밍) 언어는 언어이긴 한가 하는)"라고 적은 부분이 바로 "SQL은 사실 언어라고 보기에는 매우 단순한 명령셋의 모음일 뿐이고, 쉽게 말해 집합과 비슷하다고 보면 될거 같습니다. 원하는 데이터를 추출하기 위해 교집합, 합집합 등을 활용해 후보군을 점점 줄여 나가는데 목적이 있는, 일종의 기능 모음이죠."라고 하신 말씀 들으니까 딱 그러하다고 여겨서, 구체적이고 사실적인 표현력과 내공에 또 한번 감탄하고 감사드립니다. 

말씀하신 내용에 실무에서 자주 느끼던 바가 많이 겹치지만, 막상 이직을 앞두고는 '코딩' 테스트를 SQL로 한다니, 중요한 절차 중 하나니까 통과 압박에 부담이 크고 시험이라는 환경이 또 지원자에게 안기는 분위기란 묘하기도 해서 질문을 드렸는데, 정말 잘 질문드린 것 같습니다. 

주신 말씀 하나하나가 정말 깊이 와 닿는 부분들이고 BigQuery에서도 연습해 봐야겠습니다. 면접 팁까지 (아마 WITH문 등의 적극 활용을 말씀하시는 느낌 같기도 한데 더 연구해 보겠습니다.) 아우르는 답변 주셔서 준비하는 데 정말 유용하게 도움이 많이 되리라 생각합니다. 

다시 한번 감사드립니다! (GitHub에 이슈를 잘못 게시하면 지워지지를 않나 보네요, 중복으로 실수로 올려서 죄송합니다.)
