### ISSUE TITLE
typo p.161

### ISSUE THREAD

**Issue by Junyeopp** [onlybooks/algorithm-interview#23]
p.161 슬라이딩 윈도우가 우측으로 이동하는 코드에서 expand(s, i , i + 1)로 표기되어 있습니다.
반면에 전체코드에서는 expand(i, i + 1)로 표기되어 있습니다.

expand가 정의된 것을 보면 expand(i, i + 1)이 맞는 것으로 보입니다. 감사합니다.

**Comment by likejazz** [comment]
말씀하신대로 p161에서 조각 코드 또한 다음과 같이 수정되는게 맞겠습니다.
```python
for i in range(0, len(s) - 1):
    result = max(result,
                          expand(i, i + 1), 
                          expand(i, i + 2), 
                          key=len)
return result
```
정오표에 반영하겠습니다.
알려주셔서 감사합니다.
