### ISSUE TITLE
640쪽 그림23-9에 오류가 있는것 같습니다.

### ISSUE THREAD

**Issue by alinghi** [onlybooks/algorithm-interview#26]
계단 오르기 문제 브루트포스 그림 23-9 루트 밑 노드가
n계단->n-1계단, n-1계단이 아니라 n계단-> n-1계단, n-2계단으로 나누어져야 될것 같습니다.

좋은 책 써주셔서 감사합니다.

**Comment by likejazz** [comment]
알려주셔서 감사합니다.
확인해보니 말씀하신대로 우측 자식 노드가 `n-2`여야 하는데, `n-1`로 잘못되어 있네요.
정오표에 반영하겠습니다. 감사합니다.
