### ISSUE TITLE
88번 집 도둑 코드에 대해 문의드립니다.

### ISSUE THREAD

**Issue by MyeongJin-Kim** [onlybooks/algorithm-interview#28]
타뷸레이션을 활용한 두 번째 풀이가 leetcode에서 KeyError :0 에러를 발생시키고 동작이 되지 않습니다.

**Comment by likejazz** [comment]
안녕하세요.
책에 코드는 정상인데, 깃헙 코드에 변수명 오타가 있었네요.
수정하였습니다.
알려주셔서 감사합니다.

https://github.com/onlybooks/algorithm-interview/commit/c5af14f6a81406b8f2be2cffb11fe3a223da6acf
