### ISSUE TITLE
입력값 처리

### ISSUE THREAD

**Issue by likejazz** [onlybooks/algorithm-interview#3]
안녕하세요 책을 재미있게 공부하고 있는 학생입니다. 책의 코드를 공부하다보니 입력과 출력에서 input()을 이용하지 않고 함수를 통한 풀이에 의문을 갖게 되었습니다. 리트코드에 들어가서 다른 분들의 풀이를 보니 거의 다 함수를 이용해서 풀이하셨더군요 코딩 테스트 때도 입력이라는 단어에 크게 의미를 두지 않고 함수로 풀이해도 되는 건가요?

_Originally posted by @chanmin01 in https://github.com/onlybooks/algorithm-interview/issues/2#issuecomment-661693354_

**Comment by likejazz** [comment]
@chanmin01
안녕하세요.
리트코드에서는 입력값이 함수의 인자로 주어집니다. 예를 들어, 우리 책 첫 번째 문제인 '유효한 팰린드롬'의 경우,
```
def isPalindrome(self, s: str) -> bool:
```
에서 `s`에 입력값이 들어오게 됩니다. 그러나, 이 부분은 플랫폼 마다 모두 제각각이므로 코딩 테스트 시에는 각각의 특징을 잘 파악해야 합니다. 코딩 테스트를 치르기에 앞서 각각의 플랫폼의 특징을 충분히 숙지하시기 바랍니다.

**Comment by chanmin01** [comment]
그렇군요!! 친절한 답변 감사합니다!!
