### ISSUE TITLE
35번 "조합" 문제에 관해 질문드립니다.

### ISSUE THREAD

**Issue by joongminpark** [onlybooks/algorithm-interview#30]
안녕하세요, 좋은 서적 출판해주셔서 정말 감사드립니다.

**35번 풀이 1**에 대한 질문이 있습니다.
아래 코드에서 k == 0 이 될 때, return 으로 백트래킹을 해야,
search space가 줄어들어 연산량이 조금이라도 줄지 않을까 해서 질문드립니다.
(return 하지 않을시 순열과 동일한 연산량..?)
혹시, 제가 생각하지 못한 오류 부분이 있는지 궁금합니다.
물론 **35번 풀이 2** 의 itertools 모듈을 활용하는 것보다는 느리지만 
기존의 **풀이 1** 보다는 빠른 것 같아서요.

읽어주셔서 감사합니다.
```
from typing import List


class Solution:
    def combine(self, n: int, k: int) -> List[List[int]]:
        results = []

        def dfs(elements, start: int, k: int):
            if k == 0:
                results.append(elements[:])
                # k개 찾은 후 백트래킹 (아래 for문 실행 막음)
                return

            # 자신 이전의 모든 값을 고정하여 재귀 호출
            for i in range(start, n + 1):
                elements.append(i)
                dfs(elements, i + 1, k - 1)
                elements.pop()

        dfs([], 1, k)
        return results
```

**Comment by likejazz** [comment]
좋은 지적 감사합니다.
책 본문에도 '빠져나가는 로직'이라 언급했고, 원래 `return`을 표시했어야 하나 제가 누락한거 같네요.
다행히 0 보다 작은 값이 되어도 아무런 처리 없이 그냥 bypass 됩니다만 불필요한 연산이 일어나는게 맞습니다.

코드 및 책 본문에서도 수정하도록 하겠습니다.
감사합니다.
