### ISSUE TITLE
P174. 풀이 2 반환형

### ISSUE THREAD

**Issue by WonJongWoon** [onlybooks/algorithm-interview#32]
P173의 **"두 수의 합"** 문제의 리트코드에서 제시하는 함수의 반환형은 **List[int]** 입니다.

하지만 해당 문제의 풀이2, 풀이3, 풀이 5들은 다음과 같이 **Tuple[int]** 를 반환하고 있습니다.

```python
# 풀이 2
return nums.index(n), nums[i+1:].index(complement) + (i+1)
# 풀이 3
return nums.index(num), nums_map[target - num]
# 풀이 5
return left, right
```
풀이 1, 풀이4의 경우는 리트코드에서 제시하는 바와 같이 **List[int]** 을 반환하고 있습니다.
```python
# 풀이1
return [i, j]
# 풀이 4
return [nums_map[target - num], i]
```
이전에 올라왔던 이슈 중 그룹 애너그램 문제과 동일한 이슈인 것 같습니다. 

이 문제 말고도 일부 문제에서 List를 요구하는데 Tuple을 반환하는 경우가 빈번한 것 같습니다. 

큰 문제는 아니지만, 리트코드가 제시하는 타입에 맞추는 것이 책의 전체 일관성이나, 

제출에도 좋은 것 같아서 이슈를 작성하여 봅니다.

**Comment by likejazz** [comment]
네, 좋은 지적입니다.
모두 타입 힌트에서 지정한대로 `List[int]` 형태로 변경하는게 맞겠습니다.
코드와 책의 본문 모두 정오표에 반영하도록 하겠습니다.
감사합니다.

**Comment by daeungdaeung** [comment]
good comments, good guys

**Comment by ubless607** [comment]
@likejazz 174번 return 값을 `[i, nums.index(complement)]`로 작성하면 더 간결한 답이 될 수 있다고 생각합니다. 혹시 제가 놓친 부분이 있을까요?
