### ISSUE TITLE
담지 못하신 주제 관련

### ISSUE THREAD

**Issue by doljae** [onlybooks/algorithm-interview#33]
안녕하세요.
우선 이런 책을 내 주신 것에 대해 감사 말씀을 드립니다.
현업에 계신 분이 경험을 녹여 내에 많은 시간과 노력을 들이셨다는 것을 조금만 읽어도 느낄 수 있었습니다.

다름이 아니라 혹시 책에서 분량 문제 등의 제약 조건으로 인해 다루지 못했 던 주제가 있으셨다면, 어떤 것이 있으셨는지 궁금합니다.
다루는 주제가 알고리즘기법 자체로만 볼 때는 초급과 중급에 걸쳐있는 것 같습니다.
하지만 이번 K사 시험에서 구간트리가 나왔다는 등 중급 이상의 알고리즘이 실제 시험에서 사용되고 있는 상황인데,
혹시 담지 못하신 주제가 있다면 어떤 것들이 있을지, 또는 추후에 2편 계획이 있으신지 궁금합니다.

좋은 하루 되세요.

**Comment by likejazz** [comment]
안녕하세요.
같은 질문을 받은 기억이 나는데, 깃헙 이슈에는 안보이는거 보니 아마 다른 채널에서 답변을 드린거 같네요.

먼저, 말씀하신대로 이 책은 초중급에 눈높이를 맞췄고, 담지 못한 알고리즘이 훨씬 더 많습니다. 욕심 같았으면 지금 보다 두 배는 더 많은 분량을 담아낼 수 있었는데, 그렇다면 지금 보다 훨씬 더 어렵고, 안팔리는 ^^ 책이 되었겠죠.

이번에 다루지 못한 훨씬 더 어려운 고급 알고리즘 들을 다루면 저 또한 많은 자극이 되겠지만 지금도 어렵다는 반응이 대부분을 차지하는 터라 아마 훨씬 더 안팔리는 책이 될거 같아요. 저는 그렇다 치더라도 출판사에서는 원하는 책이 아닐거 같네요. 책 내용을 보면 아시겠지만 적어도 1년 이상 꾸준히 집필해야 하는 내용이고, 출판사 또한 잘 팔리는 책 이어야 하기 때문에 이 보다 더 어려운 책은 적어도 국내에서는 나오기 힘들지 않을까 생각합니다. 

그러나, 저는 마음 한 켠에는 항상 더 어려운 알고리즘, 더 지적 자극을 줄 수 있는 알고리즘을 원하고 있습니다.
이 정도로 답변이 되었을지 모르겠습니다. 감사합니다.

**Comment by doljae** [comment]
역시 나름의 사정이 있네요.
사실 개인 사용 용도로 중, 고급 알고리즘의 스니펫을 만들고 있습니다.
대부분 접할 수 있는 자료(책, 구글링 포함)가 c++로 작성되어있어 이를 참고해서 작성하고 있습니다.
특정 알고리즘의 경우 Python 내장 라이브러리와 지원 문법을 사용하면 훨씬 편하고 직관적으로 작성을 할 수 있을 것 같아서 현업에서 테스트를 관리하셨던 저자님께서 다루신다면 어떻게 작성하실까라는 생각을 하고 기대를 담아 여쭤봤습니다 ^^;

또 Python 언어 자체를 다루는 내용이 정말 흥미롭게 읽었습니다. 언어 구현 방법 등 깊게 파고들어 나오는 정보는 여전히 한글로 이해하기 쉽게 잘 정리가 되어있는 자료는 부족한 것 같습니다. 이런 부분만 따로 모아서 언어별로 책 같은게 나오면 반드시 필구하겠습니다 ㅎㅎ

답변 감사합니다. 좋은 하루 되세요!
