### ISSUE TITLE
219쪽 reverse(head) 오류나는데 확인해주실수있나요?

### ISSUE THREAD

**Issue by ggyudongggyu** [onlybooks/algorithm-interview#36]
219쪽 reverse(head) 오류나는데 확인해주실수있나요?
reverse 함수는 인자 2개 받는 함수로 구성했는데 왜 head 하나만 들어가는지도 모르겠습니다.

**Comment by likejazz** [comment]
책에서 모든 풀이는 편의상 항상 반복되는 `class Solution:`을 생략하였습니다.
이 부분에 대한 설명은 책 31페이지에 있습니다. 읽어보시고 차근차근 따라해보시면 될 것 같습니다.

깃허브에는 그대로 실행가능한 완전한 형태의 코드가 정리되어 있으니,
깃허브 코드를 그대로 복사해서 입력해보시면 실행되는 모습을 확인할 수 있습니다.

**Comment by ggyudongggyu** [comment]
확인해주셔서 감사합니다만 깃허브코드를 그대로 복사해서 입력해도 에러가 나서 추가질문드립니다..
왜인지 제 컴퓨터에서는 타입힌트에서 계속 syntax error가 나서 타입힌트를 뺀 채로 입력하는 중인데 혹시 이때문에 정상적으로 처리가 안될 수도 있나요? 그렇다면 head, node, prev가 ListNode클래스라는 걸 하나하나 다 선언해주어야하나요?

**Comment by likejazz** [comment]
깃허브의 코드는 리트코드에 입력할때를 기준으로 했으며, 로컬에 입력할때는 당연히 환경에 따라 적절히 코드의 추가, 수정이 필요할 수 있습니다. 리트코드에서 기본적으로 `import` 해주는 라이브러리는 책 34페이지에서 확인할 수 있으며, 로컬에서 실행시에는 이 모든 `import`를 직접하고 `ListNode` 선언 또한 모두 필요합니다. 깃허브에 있는 코드는 현재까지 발견된 오류는 모두 수정한 상태이며 제대로 실행이 되는 코드 입니다. 많이 어렵지 않으니 하나씩 따라해보면서 차근차근 학습해보시기 바랍니다.

**Comment by ggyudongggyu** [comment]
친절히 답변해주셔서 감사합니다
