### ISSUE TITLE
p.175 오타는 아니지만..

### ISSUE THREAD

**Issue by PudgeKim** [onlybooks/algorithm-interview#39]
for i, num in enumerate(nums):
  if target-num in nums_map and i != nums_m-nuap[target-num]:
    return nums.index(num), nums_map[target-num]

여기서 마지막 부분인 nums.index(num)는 그냥 i로 해도 되지않나요? 이게 좀 더 가독성이 좋지않나 싶어서.. ㅎㅎ

**Comment by likejazz** [comment]
네, 말씀하신대로 수정하는 편이 가독성도 좋고 성능도 좀 더 좋아질 수 있겠네요.
알려주셔서 감사합니다. 반영하도록 하겠습니다.
