### ISSUE TITLE
코딩테스트 문의

### ISSUE THREAD

**Issue by kimtaehyeong** [onlybooks/algorithm-interview#4]
안녕하세요.
일단 좋은 책 써주셔서 감사하게 읽고있습니다.
읽다보니 조금 잘못된 정보가 있는것 같아 여기에 문의 남김니다.

p44 경우, 삼성전자는 자체 플랫폼을 이용하지만, 상시테스트, 역량테스트(공채) 의 경우 python으로 풀이가 가능합니다.
또한 SWEA에서도 python으로 풀이가 가능한 문제들이 있으며, 상시테스트 같은경우 A형 B형 C형 등급이 나뉘게 되는데 A형의 경우 python이 가능하고 B형 C형 같은 경우가 python 이 불가능합니다. 혹시나 오해할 경우가 생길것 같아 이렇게 글 남김니다.

**Comment by likejazz** [comment]
알려주셔서 감사합니다.

전현직 직원들을 대상으로 크로스 체크를 했으나 미비한 부분이 있었던거 같네요.
해당 사항은 추가 확인을 거친 후 추후 개정판에 반영될 수 있도록 하겠습니다.

감사합니다.
