### ISSUE TITLE
16장 트라이 473쪽 질문있습니다.

### ISSUE THREAD

**Issue by legendhangkali** [onlybooks/algorithm-interview#40]
단업 삽입 부분 코드에서 node.val = char 라는 부분이 있습니다. 그런데 트라이를 저장할 노드 부분에서는 val을 정의하고 있지 않아 의문이 들었습니다. 그래서 제가 직접 node.val = char 부분을 제거하고 실행한 결과 오류없이 잘 실행되는 것도 확인했습니다. 
혹시나 제가 놓친 부분이 있는지 있다면 어떤 부분인지 설명을 듣고 싶어서 글을 남겼습니다.

**Comment by likejazz** [comment]
네, 코드를 구현하는 과정에서 노드의 값을 보관하기 위해 `.val`을 만들어 두었는데, 지금은 추가만 할뿐 정작 코드에서는 추출해서 쓰지는 않기 때문에 현재는 필요가 없습니다. 오류가 발생하지는 않지만 쓰이는 값은 아니기 때문에 삭제하도록 하겠습니다. 알려주셔서 감사합니다.

**Comment by legendhangkali** [comment]
답변 감사합니다!
