### ISSUE TITLE
p502 오타가 있는 것 같습니다.

### ISSUE THREAD

**Issue by legendhangkali** [onlybooks/algorithm-interview#41]
p502 풀이 2의 3번째 문단 2번째 줄에 **_'만약 다음번 head도 cur보다 작은 상태라면 굳이 되돌아가지 않아도 되지 않을까?'_** 와 해당 문단의 마지막 2번째 줄에는 **_'되돌아가는 경우는 cur가 head보다 클 때만 하면 될 것 같다.'_** 이 두 문장은 `if head.val < cur.val` 의 조건에서 **되돌아가지 않는다** 와 **되돌아간다** 두 가지를 모두 지칭하고 있어 오타라고 생각합니다.

**Comment by likejazz** [comment]
`만약 다음번 head도 cur보다 작은 상태라면 굳이 되돌아가지 않아도 되지 않을까?`
->
`만약 다음번 head도 cur보다 큰 상태라면 굳이 되돌아가지 않아도 되지 않을까?`
로 수정하는게 맞겠습니다. 다음 개정판에도 반영하도록 하겠습니다.
알려주셔서 감사합니다.
