### ISSUE TITLE
7번 문제 두 수의 합 3번 풀이 질문

### ISSUE THREAD

**Issue by arctan-seok** [onlybooks/algorithm-interview#42]
해답코드중 마지막 두줄
if target - num in nums_map and i != nums_map[target - num]:
    return **nums.index(num)**, nums_map[target_num] 에서

저는 코드를 이렇게 작성한 이유는 값이 같은 두 수의 합이 정답이어서 딕셔너리에서 첫번째 숫자의 인덱스가 두번째 숫자의 인덱스로 덮어씌일을 때를 고려해서 짠 코드라고 이해했는데요, 
볼드처리한 nums.index(num)은 굳이 index함수를 사용한 이유를 잘 모르겠습니다.

index값이 왼쪽부터 값을 찾아주기 때문에 첫번째 값의 인덱스를 리턴해서 index함수를 사용한 건가요??
그렇다면 그냥 nums.index(num) 대신 i를 사용하면 되지 않나요?
코드를 return **i**, nums_map[target_num] 로 바꿨을 때도 문제없이 동작해서 index 함수를 사용한 의도가 궁금해서 질문 드립니다.

**Comment by likejazz** [comment]
네, 맞습니다. `i`를 사용해도 충분한 경우였고, 깃허브 코드는 다음과 같이 수정하였습니다.
https://github.com/onlybooks/algorithm-interview/issues/39

책 또한 다음 개정판에 반영하도록 하겠습니다.
알려주셔서 감사합니다.
