### ISSUE TITLE
56page 에 오타가 있어요

### ISSUE THREAD

**Issue by therealnlee** [onlybooks/algorithm-interview#46]
사소한 거긴 하지만..
루프문 java 예시에 닫힘 중괄호(})가 빠져있습니다.

![20201025_123926](https://user-images.githubusercontent.com/37063894/97098350-4c52ee00-16bf-11eb-8ad2-6cbe582663d1.jpg)

**Comment by likejazz** [comment]
정오표에 반영하겠습니다.
알려주셔서 감사합니다.
