### ISSUE TITLE
101쪽 비문 수정

### ISSUE THREAD

**Issue by therealnlee** [onlybooks/algorithm-interview#47]
![20201025_163544](https://user-images.githubusercontent.com/37063894/97101378-3e619500-16e0-11eb-90c6-7bd19091d8ae.jpg)

리스트에서 최댓값 또는최솟값 경우가
-> 리스트에서 최댓값 또는 최솟값**을 찾는** 경우가
로 수정해야 더 자연스러울 것 같네요

**Comment by likejazz** [comment]
정오표에 반영하겠습니다.
알려주셔서 감사합니다.
