### ISSUE TITLE
P549 오타있습니다.

### ISSUE THREAD

**Issue by legendhangkali** [onlybooks/algorithm-interview#49]
p549에 마지막 OR연산 결과를 보여주는 곳에
`5 & -4`
->
`5 | -4`
로 바꿔야 할 것 같습니다.

**Comment by likejazz** [comment]
네, 말씀하신대로 `5 | -4`가 맞습니다.
정오표에 반영하도록 하겠습니다. 알려주셔서 감사합니다.
