### ISSUE TITLE
재귀에 관한 질문입니다.

### ISSUE THREAD

**Issue by PudgeKim** [onlybooks/algorithm-interview#50]
책에 재귀로 푼 코드를 보면 설명란 종종 재귀가 간단하고 우아한 코드라고 나옵니다.
그런데 인터넷에 보면 실무에서는 재귀는 코드를 작성한 사람만 편해서 잘 안쓰인다고 그러던데
사실인가요? 물론 이진트리 같은 경우야 당연히 재귀가 쓰이지만 그외에 고급?알고리즘 등을 짤 때 실무에서도 재귀가 빈번하게 사용되는지 학생입장에서 궁금합니다.

**Comment by likejazz** [comment]
책에는 재귀와 반복 구현 코드가 계속해서 번갈아가며 등장하는데요. 자세히 보시면 둘의 장단점을 어렵지 않게 확인하실 수 있습니다. 재귀를 간단하고 우아하다고 표현한 이유는 일단 코드가 훨씬 더 짧고 무엇보다 빈틈 없이 꽉 짜여 있습니다. 흔히 우리가 더 이상 뺄 것도, 넣을 것도 없는 상태를 완벽하다고 표현하는데요. 이런 코드를 보면 우아하다는 느낌을 받곤하죠. 재귀 코드를 보면 대부분 그렇습니다. 반면, 바꿔 말하면 이 얘기는 추가, 삭제가 쉽지 않다는 얘기이기도 합니다. 심지어 디버깅 코드조차 넣기가 어렵습니다. 따라서, 평소 재귀에 대한 훈련이 많이 되어 있지 않거나 대부분의 보통 사람들은 재귀를 보면 어렵다고 느끼게 됩니다. 사람마다 다르겠으나 실무에서는 혼자서만 개발하는건 아니기 때문게 다른 사람도 이해가 쉽도록 저 또한 꼭 필요한 경우가 아니라면 대부분 반복으로 구현하는 편입니다.
