### ISSUE TITLE
p.307 문제 확인바랍니다.

### ISSUE THREAD

**Issue by DevooKim** [onlybooks/algorithm-interview#51]
교재에는 "k번 이상 등장하는 요소를 추출하라." 라고 되어있습니다.
하지만 leet코드 347번의 문제의 번역과 교재의 예제코드를 보면 "많이 등장하는 순서대로 k개 추출하라."가 맞지 않을까요?

**Comment by likejazz** [comment]
네, 맞습니다. '많이 등장하는 순서대로 k번 추출하라'의 의미이고 여기서는 '상위 k번 이상 ...'의 의미로 사용했습니다. '상위 3번'이 3개 이상을 의미하진 않기 때문입니다. 그런데 말씀하신대로 '상위'를 제외하니 의미가 좀 모호해진거 같습니다. 따라서 다음과 같이 수정하도록 하겠습니다.

--
p307. k번 이상 등장하는 -> 상위 k번 이상 등장하는
k번만큼 추출하면 -> 상위 k번만큼 추출하면

p309. k 빈도 이상의 -> 상위 k번만큼의
--

알려주셔서 감사합니다.
