### ISSUE TITLE
P.146 에서 질문 드립니다.

### ISSUE THREAD

**Issue by hwangjeongwoo** [onlybooks/algorithm-interview#52]
안녕하세요.

P.146에서 
s[:] = s[::-1] 코드는 파이참에서 아래와 같은 error가 발생하는데, 
리트코드에서는 사용 가능하다고 말씀하신 것으로 이해하였습니다.

이건 리트코드의 문제인지, 
아니면 python 관련하여 제가 모르는 부분에 의해 발생하는 차이인지 문의 드립니다.

Traceback (most recent call last):
  File "C:/Users/User/PycharmProjects/pythonProject/main.py", line 21, in <module>
    s[:] = s[::-1]
TypeError: 'str' object does not support item assignment

감사합니다.

**Comment by legendhangkali** [comment]
제가 답글을 남기는게 조금 주제 넘을 수도 있지만 제가 아는 선에서 말씀을 드리자면 해당 오류는 자료형이 맞지 않거나 함수 호출 규약을 틀렸을 경우에 나타나는 오류로 알고 있습니다. 예를 들어 `s = ["h","e","l","l","o"]` 이런식으로 리스트로 되어 있어야 `s[:] = s[::-1]` 와 같은 슬라이싱이 가능하다는 말입니다.
혹 's' 가 리스트로 되어있지 않고 문자열로 되어있으면 슬라이싱이 불가능합니다. 

제가 글쓴분의 전체적인 코드를 알 수 없어 정확하게 답변은 불가능 하지만 간단하게 예시를 들자면,
`s = "hello"`
`s[:] = s[::-1]`
위와 같은 경우에는 슬라이싱이 불가능하고

`s = ["h","e","l","l","o"]`
`s[:] = s[::-1]` 
이런 경우에는 가능하다는 말이었습니다.
부족한 설명 들어주셔서 감사합니다.

**Comment by hwangjeongwoo** [comment]
네, 답변 감사합니다.

말씀하신 것처럼 저는 문자열에 대한 슬라이싱인 줄 알았는데,
지금 책을 다시 보니 다음 문구를 제대로 못봤네요.
"만약 입력값이 문자열이라면 앞서 살펴본 바와 같이 문자열 슬라이싱을 사용할 수 있다.
 **슬라이싱은 리스트에도 사용할 수 있으며, 성능 또한 매우 좋다.**
s = s[ : :-1]"

**Comment by likejazz** [comment]
@legendhangkali 답변 감사드립니다.
말씀하신대로 책 p146에서 `s`는 `List`입니다. 그래서 `s[:] = s[::-1]`가 가능하지만 아마 @hwangjeongwoo 님이 작성하신 코드에서는 `s`를 `str`로 선언한 것으로 보입니다. `str`은 불변 객체(immutable object, p110 참고)로 변수내의 값을 조작할 수 없습니다. `s = s[::-1]` 이런 형태로 완전한 재할당만 가능합니다.

감사합니다.

**Comment by hwangjeongwoo** [comment]
네, 확인 감사드립니다!!
