### ISSUE TITLE
p232 그림 8-6 재귀로 스왑하는 구조

### ISSUE THREAD

**Issue by PARKINHYO** [onlybooks/algorithm-interview#56]
안녕하세요. 수고 많으십니다. 
페어의 노드 스왑문제에서 제가 그림을 그려봤을 때는 두 번째 재귀에서 반환할 때 return p로 4를 반환하게 되어서 그림의 1) 쪽에 1이 4를 가리켜야 되는 거 같은데 맞을까요??

**Comment by likejazz** [comment]
그림에서 x축은 입력순서로 가정했습니다. 그래서 1)에서 첫 번째가 세 번째로 이어진다는걸 표현했고, 마지막에 5)에서 두 번째가 첫 번째 자리로 올라서면서 비로소 스왑이 완료되는걸 표현했습니다.

**Comment by PARKINHYO** [comment]
감사합니다!
