### ISSUE TITLE
p.222 타입힌팅 오타

### ISSUE THREAD

**Issue by arctan-seok** [onlybooks/algorithm-interview#60]
def toList(self, node: ListNode) -> ListNode: 로 되어있는데 -> List가 맞지 않나요?

**Comment by onlybooks** [comment]
안녕하세요. 책만 출판사입니다.
알려주셔서 감사합니다. 말씀주신 내용이 맞습니다.  

> **def toList(self, node: ListNode) -> ListNode**
> ->
> **def toList(self, node: ListNode) -> List:**

이외 오류사항을 등록한 정오표 페이지를 안내드리오니 참고 부탁드립니다.
https://www.onlybook.co.kr/entry/algorithm-interview-errata?category=738133
