### ISSUE TITLE
p.450 오타

### ISSUE THREAD

**Issue by arctan-seok** [onlybooks/algorithm-interview#61]
def _perlocate_up(self): 에서 while parent >= 0: 으로 적혀있는데 p.454.의 코드는 while parent > 0: 으로 되어있네요
후자가 옳은 코드같아서 오타 제보드립니다

**Comment by PARKINHYO** [comment]
#48 어떤 분이 오타를 제보해주셔서 정오표에 반영하겠다고 합니다...!!
[파이썬 알고리즘 인터뷰 정오표](https://www.onlybook.co.kr/entry/algorithm-interview-errata?category=738133)  ← 여기에 적혀있습니다😊

**Comment by likejazz** [comment]
@PARKINHYO 네, 맞습니다. 확인해주셔서 감사합니다.
