### ISSUE TITLE
P.30 1번 문제 runtime

### ISSUE THREAD

**Issue by dongjay00** [onlybooks/algorithm-interview#62]
![image](https://user-images.githubusercontent.com/68373235/101880793-d525da80-3bd6-11eb-8f31-6cb5d4e428cc.png)

책에 있는 코드와 동일하게 코드를 작성하고 제출했는데, 책과는 달리 아주 빠른 시간으로 찍혔습니다. 같은 코드인데 어떻게 저런 현상이 벌어진건가요?

**Comment by likejazz** [comment]
two sum 문제는 리트코드의 1번 문제이고 가장 많은 사람들이 풀이하는 유명한 문제이다 보니 아마도 서버 부하를 줄이기 위해 테스트케이스를 대폭 삭제한걸로 추정됩니다. 다른 풀이도 전부 빨리 풀이되는걸로 봐서 two sum 문제는 아쉽게도 풀이에 따른 변별력이 사라져 버렸네요.
