### ISSUE TITLE
p.644 그림 오류& 코드 질문

### ISSUE THREAD

**Issue by PudgeKim** [onlybooks/algorithm-interview#63]
p.644에  그림 23-11 합 부분이 9 18 18로 되어있는데 9 18 17이 맞네요
그리고 코드에서 딕셔너리를 썻는데 그냥 dp=[0]*len(nums) 이렇게 리스트 쓰면 orderedDict에 관한 문제도 없고 더 낫지 않나 싶습니다.

**Comment by likejazz** [comment]
p644 그림은 두 집의 합이 아닙니다. 구간내에 포함된 집에서 털 수 있는 최댓값입니다. 따라서 9 18 18이 맞습니다.
아울러 List를 사용하는 풀이도 좋네요. 그러나 여기서는 Dict로 풀이하였고, OrderedDict를 소개하였습니다.

감사합니다.
