### ISSUE TITLE
P324 DFS 재귀구조

### ISSUE THREAD

**Issue by PARKINHYO** [onlybooks/algorithm-interview#65]
```python
def recursive_dfs(v, discovered=[]):
    discovered.append(v)
    for w in graph[v]:
        if not w in discovered:
            discovered = recursive_dfs(w, discovered)
    return discovered
```
![image](https://user-images.githubusercontent.com/47745785/102357641-e36a6100-3ff1-11eb-8014-041cd7753a5a.png)
```if not w in discovered:``` → ```if w not in discovered:```
다음 페이지의 스택코드도 ```if v not in discovered:``` 형태로 되어 있고, PEP8 경고가 일어나서 개정판에 이부분도 수정하면 좋을 것 같습니다.

**Comment by likejazz** [comment]
감사합니다.
정오표에 반영하도록 하겠습니다.

**Comment by comjang2** [comment]
PEP8 해결을 위해서 매개변수 discovered에 대한 기본 값 처리도 수정이 필요합니다.
아래에 수정 코드를 첨부했습니다.
 
def recursive_dfs(v, discovered=None):
    if not discovered:
        discovered = []

    discovered.append(v)
    for w in graph[v]:
        if w not in discovered:
            discovered = recursive_dfs(w, discovered)

    return discovered
