### ISSUE TITLE
p.574 코드 timeout

### ISSUE THREAD

**Issue by PudgeKim** [onlybooks/algorithm-interview#66]
릿코드에서 테스트 케이스를 업데이트 했는지 책에 있는 코드로 제출하면 timeout이 나는데 확인한번 해주실수 있을까요?
저 같은 경우 큐말고 heap을 사용해서 제출했더니 1644ms로 통과했습니다.

**Comment by likejazz** [comment]
이 문제의 경우 책 출간 이후 테스트케이스가 추가되어 문제 난이도가 상승한 경우 입니다.
앞서 Two Sum 문제의 경우 오히려 테스트케이스가 삭제되어 문제 난이도가 낮아지면서 변별력이 사라진 바 있는데요.
(이슈 https://github.com/onlybooks/algorithm-interview/issues/62 참고)

이 문제는 반대로 난이도가 올라가서 새로운 풀이가 필요해졌네요. 이미 책이 출간된 상태에서 매 번 사이트의 변경을 따라가면서 반영할 수 없으므로, 깃헙의 코드 풀이에만 별도로 해당 사항을 표기하도록 하겠습니다. 추후 개정판이 나오게 되면 새로운 풀이를 반영하겠습니다.
감사합니다.
