### ISSUE TITLE
ch07/12-1.py max price initializing 관련

### ISSUE THREAD

**Issue by isingmodel** [onlybooks/algorithm-interview#70]
안녕하세요. 12-1, 12-2 풀이에서 max_price = 0으로 초기값을 세팅하면 항상 돈을 잃을 수 밖에 없는 데이터에 대해 제대로된 답을 주지 못합니다.
`-sys.maxsize` 등으로 세팅해야할 것 같습니다.

**Comment by likejazz** [comment]
좋은 지적입니다. 리트코드 문제에서는 별도의 제약 조건이 없기 때문에 말씀하신대로 가능한 최소 값을 지정하는게 맞겠습니다.
그러나 `-sys.maxsize`로 지정해보면 문제가 풀리지 않습니다. 왜냐면 최저 수익을 0으로 가정한 테스트케이스가 포함되어 있기 때문입니다. 문제에 제약 조건이 명시되어 있지 않은데, 정작 최저 수익은 0으로 가정하고 있으므로 이 문제는 리트코드의 실수로 봐야할거 같습니다.

**Comment by isingmodel** [comment]
그렇군요. 답변 감사합니다.
