### ISSUE TITLE
p.382 코드 질문입니다.

### ISSUE THREAD

**Issue by PudgeKim** [onlybooks/algorithm-interview#71]
1. 이전 문제(p.378의 네트워크 딜레이 문제)와 달리 이 문제에서는 전체 거리를 저장하고 있는 dist를 생략하였다고 나와있는데
그럼 이미 거리를 구한 정점도 다시 방문하는 경우가 생기니 dist를 넣는게 더 효율적이지 않나요?

예를 들면
1 -> 2  (w는 1)
2 -> 1  (w는 1)
2 -> 3  (w는 3)
이렇게 그래프가 있을 때 정점1이 시작점이라면 while문에 들어가고 정점2를 방문하게 되겠죠.
정점2의 이웃노드로는 1과 3이 있고 1과 3 모두 heappush가 된 후에,
heappop을 하면 1로 가는 경우가 더 짧기 때문에 한번 더 방문?하게 됩니다.

네트워크 딜레이 문제에서는 if node not in dist를 통해서 다시 방문하지 못하죠.
이게 제 생각인데 맞나요?

2. 아래는 위의 생각을 토대로 구현한 코드인데 submit해보면 틀린부분이 있는데 도저히 어디가 틀렸는지를 모르겠습니다.
어느 부분이 틀렸는지 알 수 있을까요? 긴 질문 읽어주셔서 미리 감사드립니다.
```
class Solution:
    def findCheapestPrice(self, n: int, flights: List[List[int]], src: int, dst: int, K: int) -> int:
        graph = collections.defaultdict(list)
        for u, v, w in flights:
            graph[u].append((v, w))
        
        dist = collections.defaultdict(int)
        heap = []
        heapq.heappush(heap, (0, src, K))
        
        while heap:
            price, node, live = heapq.heappop(heap)
            if node == dst:
                return price
            if node not in dist and live >= 0:
                dist[node] = price
                for v, w in graph[node]:
                    alt = price + w
                    heapq.heappush(heap, (alt, v, live-1))
                    
        return -1
```

**Comment by likejazz** [comment]
안녕하세요?

구현하신 코드는 한 번 값을 구하고 나면 더 이상 방문하지 않도록 되어 있는데, 이 문제는 K 제한 이내에는 몇 번이나 추가로 방문해도 관계 없는 문제 입니다. 일반적으로 경유지를 추가하면 값이 커질거라고 생각하기 쉽지만 목적지까지 K=1 * price=10 인 경우 K=9 * price=1  이 전체 경로는 훨씬 더 돌아가지만 전체 price는 오히려 더 낮습니다. K가 얼마나 남았냐에 따라 해당 위치에서 price는 계속 변경될 수 있기 때문에 dist[node]에 단순히 price를 저장해서는 안됩니다. 굳이 저장한다면 dist[node, K] 와 같이 K값을 포함해서 저장해야 정답을 찾을 수 있고, 이렇게 하면 K에 따른 모든 값을 계산해야 하기 때문에 구현이 많이 복잡해질거 같네요.
