### ISSUE TITLE
카카오7번 추석트래픽 문제 질문입니다.

### ISSUE THREAD

**Issue by PudgeKim** [onlybooks/algorithm-interview#74]
어제 이 문제를 접하고 제가 생각한대로 풀었는데 프로그래머스에 제출하면 2개의 케이스가 통과를 못해서 오늘까지 계속 고민하다가 도저히 모르겠어서 도움을 요청하고자 올려봅니다..
```
def solution(lines):
    if len(lines) == 1:
        return 1

    answer = 1
    info = []
    # 시간을 밀리세컨드로 바꾸는 과정
    for line in lines:
        _, t, s = line.split()
        t = t.split(':')
        s = s[:-1]

        hour = int(t[0]) * 60 * 60
        minute = int(t[1]) * 60
        sec = float(t[2])

        end_time = int((hour + minute + sec) * 1000)
        dt2 = int(float(s) * 1000)
        start_time = end_time - dt2 + 1

        info.append((start_time, end_time))


    # 여기서부터 알고리즘
    st, end = 0, 1
    lt, rt = 0, 1
    limit = 999
    while rt < len(lines):
        if info[lt][end] + limit >= info[rt][st]:
            answer = max(answer, rt - lt + 1)
            rt += 1
        else:
            if lt == rt - 1:
                lt += 1
                rt += 1
            elif lt < rt:
                lt += 1

    return answer
```

첫번째 for문은 시간을 밀리세컨드로 변환하고 info 리스트에 (시작시간, 끝나는시간) 이렇게 담는과정이니 아래 while문만
봐주시면 될 것 같습니다.

제가 생각한 알고리즘은 우선 lt는 0부터 시작하고 rt는 lt다음인 1부터 시작을 합니다.
그리고 lt에 해당하는 곳의 끝나는시간+999ms와 rt의 시작시간을 비교해서 rt를 확장해나가다가
더이상 확장을 못하면 lt를 줄이고 다시 비교해서 rt를 늘려보고 하는식으로 판별해서 O(N)에 가능할거같은 알고리즘인데
막상 돌려보면 위에 말했듯이 2개의 케이스를 통과하지못하더라구요.
도저히 어디가 잘못됬는지를 모르겠습니다..

** if lt == rt-1 이 부분은 rt는 항상 lt보다 앞에 있어야 되므로 lt가 rt와 같아지는 경우가 생기면 rt도 한칸 전전시킨부분입니다.

**Comment by likejazz** [comment]
안녕하세요.

이곳은 책에 대한 문의를 하는 곳이며, 개인적인 풀이를 봐드리는 공간이 아닙니다.
지난 번에도 풀이를 살펴 봐달라고 해서 한 번 봐 드린 적이 있는데요. 이렇게 계속해서 개인적인 풀이를 봐 드릴 수는 없습니다. 저 또한 다른 사람의 풀이를 살펴 보는 것은 시간이 많이 걸리는 일이므로 양해를 부탁드립니다.

**Comment by PudgeKim** [comment]
앗.. 죄송합니다!
