### ISSUE TITLE
57번 문제 시간복잡도 질문

### ISSUE THREAD

**Issue by arctan-seok** [onlybooks/algorithm-interview#75]
책에서 O(k^2 n)이 나온다고 적혀있는데 잘 이해가 안갑니다.
왜 이렇게 구해지는지 설명해주실 수 있을까요?

**Comment by arctan-seok** [comment]
코드를 계속 보다보니 이해가 갔습니다.
하나의 단어를 트라이에 넣는 시간 복잡도가 O(k^2)이고 이걸 트라이를 만들기 위해 모든 단어들에 반복하니 O(k^2*n)이 나오고
팰린드롬을 모두 찾는 연산은 시간이 별로 안걸려서 무시해서, 결과적으로 O(k^2*n)이 나온다고 이해했는데 맞게 이해한거겠죠?

**Comment by likejazz** [comment]
안녕하세요.

시간복잡도를 분석하는 가장 좋은 방법은 실제로 n을 정의해서 몇 번이나 계산을 하는지 출력해보는 방법입니다. 다양한 입력값에 대해 여러번 실험을 해보면 얼마나 계산이 진행되는지 쉽게 확인할 수 있고, 저도 자주 사용하는 방법입니다.
