### ISSUE TITLE
p.297 해시 테이블 디자인

### ISSUE THREAD

**Issue by Gmelon** [onlybooks/algorithm-interview#78]
마지막 remove 함수에 대한 질문입니다.

key가 hash로 변환되어 해시 테이블에 저장되므로 해당 hash가 해시 테이블에 존재한다고 해도
연결 노드 탐색 중에 key가 마지막까지 발견되지 못하는 경우가 있을 수 있지 않나요?

remove 함수의 마지막 while 문이 끝나고 끝까지 탐색을 완료하였는데도 해당 key를 발견하지 못하는 경우에 대비하여
아래와 같이 return 구문을 적어주어야 하는 것이 아닌지 질문드립니다.

```
while p:
    if p.key == key:'
        prev.next = p.next'
        return'
    prev, p = p, p.next'
return
```

**Comment by likejazz** [comment]
안녕하세요?

remove 함수의 리턴 타입은 None 입니다.
`def remove(self, key: int) -> None:`
따라서 리턴이 필요 없습니다. 
아울러 파이썬에서 마지막 단순 return은 생략 가능하며 동일하게 동작합니다.
