### ISSUE TITLE
146p 트릭관련 질문

### ISSUE THREAD

**Issue by hwi-middle** [onlybooks/algorithm-interview#79]
146쪽에 보면 s = s[::-1]은 제약사항때문에 안되는데 왜 s[:] = s[::-1]은 되나요? 그리고 s[:]는 사본을 리턴한다고 했는데 뒤집은 문자열을 사본에 대입하는것 아닌가요? 그러면 원본 문자열은 그대로일 것 같은데 이 트릭에 대해 설명을 듣고싶습니다.

**Comment by likejazz** [comment]
안녕하세요?

이 트릭은 리트코드의 제약 사항으로 인한 문제이기 때문에 제가 정확한 답변을 드리기는 어렵습니다.
예상컨데 재할당을 차단하고 s[:] 처럼 기존에 할당된 변수에 복사만 허용한게 아닌가 싶네요. 
물론 어디까지나 추측이고 자세한 사항은 리트코드에 확인이 필요할 것 같습니다.
