### ISSUE TITLE
leetcode 동영상과 "파이썬  알고리즘 인터뷰" 에 사용된 코드의 관계 목록

### ISSUE THREAD

**Issue by liganega** [onlybooks/algorithm-interview#8]
[leetcode 동영상](https://www.youtube.com/watch?v=yp1leTBR5ko&list=PL1iR1v6eNy5OO01XbQ1djo4P6gNG78wYH)에서 설명되는 코드(문제)가 책의 어디에서 사용되었는가를 보여주는 "찾아보기"(index)는 혹시 제공되지 않나요?

**Comment by likejazz** [comment]
유튜브 동영상 강의는 책과는 별개로 진행되는 강의입니다.

책에도 나와있듯 풀이 또한 책과 일치하지 않으며, 문제를 어떤식으로 풀이하는지 참고 용도로만 활용하시기 바랍니다. 유튜브 강의는 계속해서 업데이트 될 예정입니다.

감사합니다.

**Comment by liganega** [comment]
고맙습니다.
