### ISSUE TITLE
p. 331 문제 32(섬의 개수), p.319 오일러 경로

### ISSUE THREAD

**Issue by fightnyy** [onlybooks/algorithm-interview#82]
p. 331 예제 2번의 출력이 1로 되어있는데 3으로 바뀌어야 합니다.

p.319 에서 오일로 경로 증명부분에서 "오일러는 모든정점이 짝수개의 차수를 갖는다면 ...." 라고 되어있는데 
=>"1) 짝수점만으로 된 도형은 어디에서 출발하여 그려도 마지막에는 제자리로 돌아오는 한붓그리기가 가능하고, 2) 홀수점이 2개인 도형은 한쪽 홀수점에서 출발하여 나머지 홀수점에서 끝나는 한붓그리기가 가능한데, 홀수점 이외의 지점에서 출발하면 한붓그리기는 불가능하게 된다는 점이다." 로 고치시는게 좀  더 정확할거 같습니다.

**Comment by likejazz** [comment]
안녕하세요.

p331은 정오표에 반영되어 있습니다. https://www.onlybook.co.kr/entry/algorithm-interview-errata
알려주셔서 감사합니다.

p319는 좀 더 엄밀한 설명이 필요할지는 좀 더 검토해보도록 하겠습니다.
감사합니다.

**Comment by fightnyy** [comment]
오일러 경로에 대한 정의는 그래프에대한 개념을 설명할때 넣어주신거라 그렇게 엄밀한 설명은 생략하셔도 괜찮으실거 같습니다. 
다만 저 같은 경우는 친구들과 얘기를 나누고 있던 도중 "야 오일러 경로 모든 vertex의 차수가 짝수 아니면 안된데"라고 하다가 홀수인 값이 2개 여도 되는 경우를 봐서 제가 순간 개념을 잘못이해한것인가 생각하다 이에 대한 개념을 찾아보니 조금 설명이 달라서 첨부하였습니다.
답변 감사합니다.
