### ISSUE TITLE
문제 48번 코드 (p.415) 문의

### ISSUE THREAD

**Issue by NeilPark-st** [onlybooks/algorithm-interview#85]
한번이라도 -1이 나타나면 결과는 무조건 -1이라고 하셨는데
그림 14-13에서 root가 0번이 되고 루트 1번이 0번의 left child가 된다면
left = check(root.left), 즉 -1
right = check(root.right), 즉 check(None) = 0
이러면 left와 right의 차이가 1이 되어서 0을 return하게 되지 않나요?
혹시 제가 잘못 이해한 부분이 있을까요? 감사합니다

**Comment by likejazz** [comment]
안녕하세요. 한 번 -1이 되면 더 이상 회복되지 않는다는 얘기는 루트에서 부터 내려가는게 아니라 리프 노드에서 거슬러 올라가는 경우에 해당되는 얘기 입니다. 코드를 보면 리프 부터 비교하면서 루트로 거슬러 올라가게 되어 있는데, 이 경우 한 번 -1이 되면 회복되지 않고 루트까지 -1을 리턴하게 됩니다.
