### ISSUE TITLE
오탈자 제보입니다. p.211입니다.

### ISSUE THREAD

**Issue by ksundong** [onlybooks/algorithm-interview#9]
> 파이썬에서는 원시 타입(Primitive Types)이 존재하지 않**는**다.

않다.를 않는다로 고치는 것이 좋을 것 같습니다.

책 잘 읽고 있습니다. 감사합니다!

**Comment by likejazz** [comment]
감사합니다.

정오표에 반영 하였고, 다음 증쇄 시 수정하도록 하겠습니다.
