### ISSUE TITLE
10번 - 배열 파티션 I (p.192) 질문입니다

### ISSUE THREAD

**Issue by leemun1** [onlybooks/algorithm-interview#96]
안녕하세요, 먼저 좋은 책 만들어주셔서 감사드립니다.
덕분에 열심히 공부하며 많이 배우고 있습니다.

10번 문제에서 제시하신 3가지 풀이 중, 슬라이싱을 사용하는 3번 풀이에 대한 질문이 있습니다.

책에서 제시된 풀이는 다음과 같이 `sorted()` 내장 함수를 사용하는 방법인데요,

```python3
def arrayPairSum(self, nums: List[int]) -> int:
    return sum(sorted(nums)[::2])
```

이대로 리트코드에 제출을 해보았더니 260 ~300ms 정도의 실행시간이 나왔습니다.

이후, 2번 풀이에 쓰여진대로 리스트의 내장 `sort()` 를 사용하면 어떨까 싶어서 다음과 같이 제출을 해보았는데요,

```python3
def arrayPairSum(self, nums: List[int]) -> int:
    nums.sort()
    return sum(nums[::2])
```

이번엔 좀 더 느린, 420~470ms 정도의 실행시간이 나왔습니다.

왜 두 정렬 방법이 다른 실행시간이 나오는지 궁금해서 두 내장함수들의 차이를 검색해보았더니 리스트 객체 원본에 정렬을 수행하는 `sort()` 함수와 달리 `sorted()` 함수는 정렬된 사본을 만들어내기 때문에 더 느리다고 하는데, 이 설명대로라면 `sort()` 함수가 더 빠른 실행시간이 나왔어야하는데 왜 반대의 결과가 나온건지 궁금합니다.

리트코드의 채점과정이 어떻게 작동하는지 잘 모르지만 혹시 우연이었나 싶어서 각 풀이방법으로 여러번 제출해봐도 항상 위와 같은 결과가 나왔습니다. 

제가 잘못 이해했거나 놓치고있는 부분이 무엇인지 알려주시면 감사하겠습니다!

**Comment by likejazz** [comment]
제가 리트코드에 입력해봤을때는 두 번째가 더 빠르게 나왔습니다.
![Screen Shot 2021-04-14 at 7 33 03 PM](https://user-images.githubusercontent.com/1250095/114696967-3feb4c00-9d58-11eb-8d6e-aec4f3bc6523.png)
(여기서 260ms가 두 번째 함수로 제출한 결과입니다)

리트코드는 항상 일정한 실행 시간을 보장해주지는 않기 때문에 오차가 있을 수 있습니다. 또한 이 함수를 단일 입력값을 대상으로 테스트 해봤을때도 두 번째가 좀 더 빠르게 수행되었습니다.
```
%timeit -n 10000 arrayPairSum1([6, 2, 6, 5, 1, 2, 45, 8, 10, 22, 5, 9])
727 ns ± 36.2 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
%timeit -n 10000 arrayPairSum2([6, 2, 6, 5, 1, 2, 45, 8, 10, 22, 5, 9])
666 ns ± 67 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

**Comment by leemun1** [comment]
답변 감사드립니다. 말씀 주신대로 리트코드에서의 실행시간 오차 때문이었던 것 같네요.
