### ISSUE TITLE
p.201 13 팰린드롬 연결 리스트 질문 ( 234. Palindrome Linked List )

### ISSUE THREAD

**Issue by DoTheBestMayB** [onlybooks/algorithm-interview#99]
https://leetcode.com/problems/palindrome-linked-list/

리트코드 해당 문제 아래에 아래와 같은 조건으로 해결할 수 있는지 물어보는데, 풀이4 런너를 이용한 우아한 풀이는 이 조건에 해당하지 않죠?

Follow up: Could you do it in O(n) time and O(1) space?

아래 사이트에서 데이터 구조의 따른 공간 복잡도 차트에서 배열, 연결 리스트 모두 O(n)이라고 되어 있는데

https://www.bigocheatsheet.com/

시간 복잡도가 O(n) 이면서 공간 복잡도가 O(1)인 파이썬스러운 답안은 어떻게 되나요?

**Comment by DoTheBestMayB** [comment]
리트코드 공간 복잡도 O(1)은 새로운 변수(주어진 변수 값을 가리키는 것 제외)를 생성하지 않고
주어진 변수만을 가지고 해결하는걸 말하는 것 같아요.

코멘트 종료할게요

**Comment by likejazz** [comment]
@DoTheBestMayB 안녕하세요. 답변이 늦어 죄송합니다.
네, 말씀하신대로 별도로 표기하진 않았지만 런너 방식이 시간 O(n), 공간 O(1)을 만족합니다.
참고로 별도 변수를 100개쯤 사용한다 해도 입력값이 10개든, 1억개든 관계 없이 항상 일정하게 100개를 사용한다면 마찬가지로 O(1)이라고 할 수 있습니다.
